CREATE TABLE IF NOT EXISTS employees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  ssn TEXT,
  passport TEXT,
  issuing_country TEXT,
  birth_date DATE,
  origin_country TEXT,
  residence_state TEXT,
  address TEXT,
  city TEXT,
  zip_code TEXT,
  same_city BOOLEAN DEFAULT true,
  distance TEXT,
  language TEXT DEFAULT 'pt',
  photo_url TEXT,
  location TEXT,
  factory TEXT,
  project TEXT,
  role TEXT,
  department TEXT,
  supervisor TEXT,
  start_date DATE,
  end_date DATE,
  work_notes TEXT,
  hourly_rate DECIMAL(10,2),
  effective_date DATE,
  status TEXT DEFAULT 'Ativo',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
